In [12]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import scipy as sp
import scipy.linalg as splg
from numpy.random import default_rng
rng = default_rng()

In [9]:
mx = rng.standard_normal(size=(10,5))
arr = rng.standard_normal(size=5) 

mx
arr
mx.dot(arr)

array([[ 0.2903168 ,  0.32539322, -0.18627876, -0.87467764, -1.06676889],
       [ 0.54453317, -0.21552471,  1.59340777,  0.42091751,  1.40364845],
       [ 0.83469526,  1.33187826, -0.20972767, -1.13645302,  0.50267716],
       [-1.07938293, -0.7983745 , -1.71566741,  1.63390432, -1.66010799],
       [-0.93308576, -1.57865521, -0.51130259,  1.57546731, -0.05281984],
       [ 0.63514738,  0.10708489,  0.07387973, -0.47754471, -0.78995777],
       [-1.05347723,  1.75710011,  0.99308979, -0.39369959,  2.23752459],
       [ 0.87760477,  0.43225703, -0.05576531,  0.07912257, -1.38949503],
       [-1.53308574,  0.9006375 , -0.63064164,  0.79360897,  0.30023883],
       [-0.56610716, -0.22827888,  0.59393205,  0.2025367 , -0.50579677]])

array([-1.87314148, -1.5640267 , -1.81863805,  0.04619096, -0.4192307 ])

array([-0.30713442, -4.1497432 , -3.52840831,  7.16213387,  5.24165092,
       -1.18244873, -3.53713482, -1.63234879,  2.52076251,  0.55868654])

In [13]:
splg.svd(mx)

(array([[ 3.58172755e-02,  3.45512350e-01,  1.94525637e-01,
         -2.02258430e-01,  3.74464954e-01, -2.18868932e-01,
          4.49936677e-01,  1.86827324e-01,  6.08059068e-01,
         -7.33398844e-02],
        [-2.85846242e-01, -2.04770417e-01, -5.55799160e-01,
         -2.27123023e-01, -4.42480638e-01, -6.75861751e-02,
          3.24002104e-01, -3.11239483e-01,  3.33784710e-01,
         -4.74005333e-02],
        [-2.96941322e-01,  2.64947384e-01,  3.07637033e-01,
          3.83703816e-01, -2.73746028e-01, -5.22424241e-04,
          2.40753247e-01, -1.71526693e-01,  1.88466455e-02,
          6.61123048e-01],
        [ 6.19983936e-01, -1.57994250e-01,  2.78846809e-01,
         -1.80008160e-02, -2.57659955e-01, -4.57353772e-02,
          5.49672307e-01, -2.46132581e-01, -2.47864136e-01,
         -1.41210000e-01],
        [ 3.70203801e-01, -4.07460069e-01, -2.73914538e-01,
          1.72299980e-01,  2.38262115e-02,  2.31713932e-01,
          9.76899960e-02,  5.07757761e-01,  2.501101