In [17]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [1]:
import xarray as xr
import pandas as pd
import numpy as np

## DataArray
labelled multidimensional array

In [5]:
# creating xarray

arr = np.ones((10, 5))
idx = range(10)
cols = list('abcde')

darr = xr.DataArray(arr, coords=[idx, cols], dims=['index', 'field'])
darr

<xarray.DataArray (index: 10, field: 5)>
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])
Coordinates:
  * index    (index) int64 0 1 2 3 4 5 6 7 8 9
  * field    (field) <U1 'a' 'b' 'c' 'd' 'e'

In [6]:
# creating 3-dim, xarray; can have any dimension

arr = np.ones((10, 5, 5))
idx = range(10)
cols = list('abcde')
groups = list('xyzwv')

darr = xr.DataArray(arr, coords=[idx, cols, groups], dims=['index', 'field', 'class'])
darr

<xarray.DataArray (index: 10, field: 5, class: 5)>
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
...
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])
Coordinates:
  * index    (index) int64 0 1 2 3 4 5 6 7 8 9
  * field    (field) <U1 'a' 'b' 'c' 'd' 'e'
  * class    (class) <U1 'x' 'y' 'z' 'w' 'v'

In [7]:
darr.sel(field='b')

<xarray.DataArray (index: 10, class: 5)>
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])
Coordinates:
  * index    (index) int64 0 1 2 3 4 5 6 7 8 9
    field    <U1 'b'
  * class    (class) <U1 'x' 'y' 'z' 'w' 'v'

In [11]:
# coords are not necessarily equal to dims, can add constants 
# variable dependent on some of the dimes

arr = np.ones((10, 5))
idx = range(10)
cols = list('abcde')

darr = xr.DataArray(arr, coords={'index': idx, 'field':cols, 'x': 10, 'y': ('index', range(2, 12))}, dims=['index', 'field'])
darr

<xarray.DataArray (index: 10, field: 5)>
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])
Coordinates:
  * index    (index) int64 0 1 2 3 4 5 6 7 8 9
  * field    (field) <U1 'a' 'b' 'c' 'd' 'e'
    x        int64 10
    y        (index) int64 2 3 4 5 6 7 8 9 10 11

In [14]:
# can create data array from df, but need to specify index/cols names

df = pd.DataFrame(arr, idx, cols)
df.index.name = 'index'
df.columns.name = 'field'
xr.DataArray(df)

<xarray.DataArray (index: 10, field: 5)>
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])
Coordinates:
  * index    (index) int64 0 1 2 3 4 5 6 7 8 9
  * field    (field) object 'a' 'b' 'c' 'd' 'e'

In [19]:
# methods of data array
darr.values
darr.dims
darr.coords
darr.attrs

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

('index', 'field')

Coordinates:
  * index    (index) int64 0 1 2 3 4 5 6 7 8 9
  * field    (field) <U1 'a' 'b' 'c' 'd' 'e'
    x        int64 10
    y        (index) int64 2 3 4 5 6 7 8 9 10 11

{}

In [22]:
# accessing coordinates from .coords or directly

darr.coords['y']
darr['y']

<xarray.DataArray 'y' (index: 10)>
array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Coordinates:
  * index    (index) int64 0 1 2 3 4 5 6 7 8 9
    x        int64 10
    y        (index) int64 2 3 4 5 6 7 8 9 10 11

<xarray.DataArray 'y' (index: 10)>
array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Coordinates:
  * index    (index) int64 0 1 2 3 4 5 6 7 8 9
    x        int64 10
    y        (index) int64 2 3 4 5 6 7 8 9 10 11

In [24]:
darr['index']  # get all aligned coordinates with it

<xarray.DataArray 'index' (index: 10)>
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Coordinates:
  * index    (index) int64 0 1 2 3 4 5 6 7 8 9
    x        int64 10
    y        (index) int64 2 3 4 5 6 7 8 9 10 11

In [27]:
darr['field']  # get all aligned coordinates (scalar is aligned with everything)

<xarray.DataArray 'field' (field: 5)>
array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')
Coordinates:
  * field    (field) <U1 'a' 'b' 'c' 'd' 'e'
    x        int64 10

In [29]:
darr['field']['field']  # idempotent

<xarray.DataArray 'field' (field: 5)>
array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')
Coordinates:
  * field    (field) <U1 'a' 'b' 'c' 'd' 'e'
    x        int64 10

In [54]:
darr.loc[2, 'b']  # access using loc

<xarray.DataArray ()>
array(1.)
Coordinates:
    index    int64 2
    field    <U1 'b'
    x        int64 10
    y        int64 4

In [55]:
darr

<xarray.DataArray (index: 10, field: 5)>
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])
Coordinates:
  * index    (index) int64 0 1 2 3 4 5 6 7 8 9
  * field    (field) <U1 'a' 'b' 'c' 'd' 'e'
    x        int64 10
    y        (index) int64 2 3 4 5 6 7 8 9 10 11

In [57]:
dd = xr.DataArray(np.ones((3, 4, 5)), dims=['x', 'y', 'z'], coords={
    'x': range(3),
    'yz': (['y', 'z'], np.zeros((4,5)))
})

## DataSet
equivalent of multidimensional pandas df;
in DataArray there's just one multidim array (coordinates are for alignment and index, not for storing values); 
in DataSet can specify multiple arrays.

In [34]:
# creating DataSet with arrays x, y with different dimensions

x = np.ones((3, 4, 2))
y = np.ones((3, 2))

idx =  list('abc')
cols = list('XY')
fields = range(4)

ds = xr.Dataset(
    {
        'x': (['index', 'fields', 'columns'], x),
        'y': (['index', 'columns'], y),
    },
    coords={
        'index': idx,
        'columns': cols,
        'plane': (['index', 'fields'], np.zeros((3,4)))
        
    }
)
ds

<xarray.Dataset>
Dimensions:  (columns: 2, fields: 4, index: 3)
Coordinates:
  * index    (index) <U1 'a' 'b' 'c'
  * columns  (columns) <U1 'X' 'Y'
    plane    (index, fields) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
Dimensions without coordinates: fields
Data variables:
    x        (index, fields, columns) float64 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0
    y        (index, columns) float64 1.0 1.0 1.0 1.0 1.0 1.0

In [33]:
ds['fields']

<xarray.DataArray 'fields' (fields: 4)>
array([0, 1, 2, 3])
Dimensions without coordinates: fields

In [36]:
ds['x']  # getting dataarray from individuals data variables

<xarray.DataArray 'x' (index: 3, fields: 4, columns: 2)>
array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])
Coordinates:
  * index    (index) <U1 'a' 'b' 'c'
  * columns  (columns) <U1 'X' 'Y'
    plane    (index, fields) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
Dimensions without coordinates: fields

In [39]:
ds['z'] = xr.DataArray(np.ones((4, 2)), dims=['fields', 'columns'])  # can assign dataarrays to new data vars
ds

<xarray.Dataset>
Dimensions:  (columns: 2, fields: 4, index: 3)
Coordinates:
  * columns  (columns) object 'X' 'Y'
  * index    (index) <U1 'a' 'b' 'c'
    plane    (index, fields) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
Dimensions without coordinates: fields
Data variables:
    x        (index, fields, columns) float64 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0
    y        (index, columns) float64 1.0 1.0 1.0 1.0 1.0 1.0
    z        (fields, columns) float64 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0

In [43]:
ds.

<xarray.Dataset>
Dimensions:  (columns: 2, fields: 4, index: 3)
Coordinates:
  * columns  (columns) object 'X' 'Y'
  * index    (index) <U1 'a' 'b' 'c'
    plane    (index, fields) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
Dimensions without coordinates: fields
Data variables:
    x        (index, fields, columns) float64 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0
    y        (index, columns) float64 1.0 1.0 1.0 1.0 1.0 1.0
    z        (fields, columns) float64 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0

In [46]:
darr.to_dataset(name='arr')  # dataset from single array

<xarray.Dataset>
Dimensions:  (field: 5, index: 10)
Coordinates:
  * index    (index) int64 0 1 2 3 4 5 6 7 8 9
  * field    (field) <U1 'a' 'b' 'c' 'd' 'e'
    x        int64 10
    y        (index) int64 2 3 4 5 6 7 8 9 10 11
Data variables:
    arr      (index, field) float64 1.0 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0 1.0 1.0

In [51]:
ds.sel(index=ds['index'].isin(['b', 'c']))  # boolean index, using isin for dataarrays

<xarray.Dataset>
Dimensions:  (columns: 2, fields: 4, index: 2)
Coordinates:
  * columns  (columns) object 'X' 'Y'
  * index    (index) <U1 'b' 'c'
    plane    (index, fields) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
Dimensions without coordinates: fields
Data variables:
    x        (index, fields, columns) float64 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0
    y        (index, columns) float64 1.0 1.0 1.0 1.0
    z        (fields, columns) float64 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0

In [61]:
ds.dims

Frozen(SortedKeysDict({'columns': 2, 'index': 3, 'fields': 4}))

In [64]:
ds['w'] = xr.DataArray(np.zeros((4, 10)), dims=['fields', 'groups'])
ds

<xarray.Dataset>
Dimensions:  (columns: 2, fields: 4, groups: 10, index: 3)
Coordinates:
  * columns  (columns) object 'X' 'Y'
  * index    (index) <U1 'a' 'b' 'c'
    plane    (index, fields) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
Dimensions without coordinates: fields, groups
Data variables:
    x        (index, fields, columns) float64 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0
    y        (index, columns) float64 1.0 1.0 1.0 1.0 1.0 1.0
    z        (fields, columns) float64 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0
    w        (fields, groups) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0

In [65]:
ds

<xarray.Dataset>
Dimensions:  (columns: 2, fields: 4, groups: 10, index: 3)
Coordinates:
  * columns  (columns) object 'X' 'Y'
  * index    (index) <U1 'a' 'b' 'c'
    plane    (index, fields) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
Dimensions without coordinates: fields, groups
Data variables:
    x        (index, fields, columns) float64 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0
    y        (index, columns) float64 1.0 1.0 1.0 1.0 1.0 1.0
    z        (fields, columns) float64 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0
    w        (fields, groups) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0

In [69]:
ds.sel(fields=2)

<xarray.Dataset>
Dimensions:  (columns: 2, groups: 10, index: 3)
Coordinates:
  * columns  (columns) object 'X' 'Y'
  * index    (index) <U1 'a' 'b' 'c'
    plane    (index) float64 0.0 0.0 0.0
Dimensions without coordinates: groups
Data variables:
    x        (index, columns) float64 1.0 1.0 1.0 1.0 1.0 1.0
    y        (index, columns) float64 1.0 1.0 1.0 1.0 1.0 1.0
    z        (columns) float64 1.0 1.0
    w        (groups) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0

In [70]:
ds.loc[{'fields': 2}]

<xarray.Dataset>
Dimensions:  (columns: 2, groups: 10, index: 3)
Coordinates:
  * columns  (columns) object 'X' 'Y'
  * index    (index) <U1 'a' 'b' 'c'
    plane    (index) float64 0.0 0.0 0.0
Dimensions without coordinates: groups
Data variables:
    x        (index, columns) float64 1.0 1.0 1.0 1.0 1.0 1.0
    y        (index, columns) float64 1.0 1.0 1.0 1.0 1.0 1.0
    z        (columns) float64 1.0 1.0
    w        (groups) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0